### PR TITLE
fix: handle all type-only imports by piping TS imports

### LINKED ISSUE #7: Type only imports are not set as dependencies
After interface modification the plugin (v0.3.0) serves depending files from the cache, missing potentially breaking changes.

To reproduce make a clean build, break a type-only ts file and rerun a build.

### LINKED ISSUE #24: Why are interface declarations removed ?
Hi,

I'm trying to move from webpack to rollup for a library and I have trouble getting declarations to work correctly.

It seems that interfaces declarations aren't exported, this is a problem when I have things like : 

```typescript 
import { RenderedCell } from "../RenderedCell";

export default class MergedCell implements RenderedCell {
    // ...
}
```

I get the error that RenderedCell can't be found.
I worked in webpack, and I can't understand what's the difference in my configuration that broke this. but I seem to understand that it's normal with Rollup.

BTW. I'm using the latest rollup, rollup-plugin-typescript2 and rollup-plugin-uglify I can post my configurations if needed

### LINKED ISSUE #106: Source files with only type declarations don't get declarations generated
#### What happens and why it is wrong
When building a project with files that only have type declarations, the declarations don't get generated for those files. Using `tsc` generated the declarations and declaration maps as expected.

screenshot from 2018-08-23 11-21-12

#### Versions
- typescript: 3.0.1
- rollup: 0.64.1
- rollup-plugin-typescript2: 0.16.1

#### rollup.config.js
```js
import { dirname, join } from 'path';
import commonjs from 'rollup-plugin-commonjs';
import typescript from 'rollup-plugin-typescript2';
import resolve from 'rollup-plugin-node-resolve';

const root = process.cwd();
const { main, module, types, dependencies = {}, peerDependencies = {} } = require(join(root, 'package.json'));

export default {
  input: join(root, 'src/index.ts'),
  output: [
    {
      file: join(root, main),
      format: 'cjs',
      sourcemap: true
    },
    {
      file: join(root, module),
      format: 'es',
      sourcemap: true
    }
  ],
  external: [
    ...Object.keys(dependencies),
    ...Object.keys(peerDependencies)
  ],
  plugins: [
    resolve(),
    typescript({
      clean: true,
      useTsconfigDeclarationDir: true,
      tsconfigOverride: {
        compilerOptions: {
          rootDir: join(root, 'src'),
          declarationDir: join(root, dirname(types))
        }
      }
    }),
    commonjs()
  ]
};
```

#### tsconfig.json
```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "jsx": "react",
    "moduleResolution": "node",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "strict": true,
    "allowSyntheticDefaultImports": true
  },
  "include": [
    "src/"
  ]
}
```

#### package.json
```json
{
  "scripts": {
    "prebuild": "lerna exec -- rimraf lib",
    "build": "lerna exec --parallel -- rollup --config \\$LERNA_ROOT_PATH/rollup.config.js"
  },
  "devDependencies": {
    "lerna": "^3.1.2",
    "rimraf": "^2.6.2",
    "rollup": "^0.64.1",
    "rollup-plugin-commonjs": "^9.1.5",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-typescript2": "^0.16.1",
    "typescript": "^3.0.1"
  }
}
```

#### plugin output with verbosity 3
<details>
 <summary>Log</summary>

```
lerna notice cli v3.1.4
lerna info exec in 1 package: "rollup --config $LERNA_ROOT_PATH/rollup.config.js"
@: <path>/src/index.ts → lib/index.js, lib/index.es.js...
@: rpt2: typescript version: 3.0.1
@: rpt2: tslib version: 1.9.3
@: rpt2: rollup-plugin-typescript2 version: 0.16.1
@: rpt2: plugin options:
@: {
@:     "verbosity": 3,
@:     "clean": true,
@:     "useTsconfigDeclarationDir": true,
@:     "tsconfigOverride": {
@:         "compilerOptions": {
@:             "rootDir": "<path>/src",
@:             "declarationDir": "<path>/lib"
@:         }
@:     },
@:     "check": true,
@:     "cacheRoot": "<path>/.rpt2_cache",
@:     "include": [
@:         "*.ts+(|x)",
@:         "**/*.ts+(|x)"
@:     ],
@:     "exclude": [
@:         "*.d.ts",
@:         "**/*.d.ts"
@:     ],
@:     "abortOnError": true,
@:     "rollupCommonJSResolveHack": false,
@:     "typescript": "version 3.0.1",
@:     "transformers": [],
@:     "tsconfigDefaults": {}
@: }
@: rpt2: rollup config:
@: {
@:     "external": [
@:         "react",
@:         "",
@:         ""
@:     ],
@:     "inlineDynamicImports": false,
@:     "input": "<path>/src/index.ts",
@:     "chunkGroupingSize": 5000,
@:     "perf": false,
@:     "plugins": [
@:         {
@:             "name": "node-resolve"
@:         },
@:         {
@:             "name": "rpt2"
@:         },
@:         {
@:             "name": "commonjs"
@:         }
@:     ],
@:     "entry": "<path>/src/index.ts"
@: }
@: rpt2: built-in options overrides: {
@:     "noEmitHelpers": false,
@:     "importHelpers": true,
@:     "noResolve": false,
@:     "noEmit": false,
@:     "inlineSourceMap": false,
@:     "outDir": "<path>/.rpt2_cache/placeholder",
@:     "moduleResolution": 2
@: }
@: rpt2: parsed tsconfig: {
@:     "options": {
@:         "module": 6,
@:         "target": 1,
@:         "lib": [
@:             "lib.es2015.d.ts",
@:             "lib.dom.d.ts"
@:         ],
@:         "jsx": 2,
@:         "moduleResolution": 2,
@:         "declaration": true,
@:         "declarationMap": true,
@:         "sourceMap": true,
@:         "strict": true,
@:         "allowSyntheticDefaultImports": true,
@:         "rootDir": "<path>/src",
@:         "declarationDir": "<path>/lib",
@:         "configFilePath": "<path>/tsconfig.json",
@:         "noEmitHelpers": false,
@:         "importHelpers": true,
@:         "noResolve": false,
@:         "noEmit": false,
@:         "inlineSourceMap": false,
@:         "outDir": "<path>/.rpt2_cache/placeholder"
@:     },
@:     "fileNames": [],
@:     "typeAcquisition": {
@:         "enable": false,
@:         "include": [],
@:         "exclude": []
@:     },
@:     "raw": {
@:         "compilerOptions": {
@:             "module": "esnext",
@:             "target": "es5",
@:             "lib": [
@:                 "es6",
@:                 "dom"
@:             ],
@:             "jsx": "react",
@:             "moduleResolution": "node",
@:             "declaration": true,
@:             "declarationMap": true,
@:             "sourceMap": true,
@:             "strict": true,
@:             "allowSyntheticDefaultImports": true,
@:             "rootDir": "<path>/src",
@:             "declarationDir": "<path>/lib"
@:         },
@:         "include": [
@:             "src/"
@:         ],
@:         "compileOnSave": false
@:     },
@:     "errors": [
@:         {
@:             "messageText": "No inputs were found in config file '<path>/tsconfig.json'. Specified 'include' paths were '[\"src/\"]' and 'exclude' paths were '[\"<path>/lib\"]'.",
@:             "category": 1,
@:             "code": 18003
@:         }
@:     ],
@:     "wildcardDirectories": {
@:         "<path>/src/": 1
@:     },
@:     "compileOnSave": false,
@:     "configFileSpecs": {
@:         "includeSpecs": [
@:             "src/"
@:         ],
@:         "excludeSpecs": [
@:             "<path>/lib"
@:         ],
@:         "validatedIncludeSpecs": [
@:             "src/"
@:         ],
@:         "validatedExcludeSpecs": [
@:             "<path>/lib"
@:         ],
@:         "wildcardDirectories": {
@:             "<path>/src/": 1
@:         }
@:     }
@: }
@: rpt2: included:
@: '[
@:     "*.ts+(|x)",
@:     "**/*.ts+(|x)"
@: ]'
@: rpt2: excluded:
@: '[
@:     "*.d.ts",
@:     "**/*.d.ts"
@: ]'
@: rpt2: Ambient types:
@: rpt2:     <path>/node_modules/@types/estree/index.d.ts
@: rpt2:     <path>/node_modules/@types/node/index.d.ts
@: rpt2:     <path>/node_modules/@types/prop-types/index.d.ts
@: rpt2:     <path>/node_modules/@types/react/index.d.ts
@: rpt2: ambient types changed, redoing all semantic diagnostics
@: rpt2: transpiling '<path>/src/index.ts'
@: rpt2:     cache: 'cb5a72ce1d9ca58fa672e942573d3ba70cc6e65e'
@: rpt2:     cache miss
@: rpt2:     cache: 'cb5a72ce1d9ca58fa672e942573d3ba70cc6e65e'
@: rpt2:     cache miss
@: rpt2:     cache: 'cb5a72ce1d9ca58fa672e942573d3ba70cc6e65e'
@: rpt2:     cache miss
@: rpt2: generated declarations for '<path>/src/index.ts'
@: rpt2: dependency '<path>/src/constants.ts'
@: rpt2:     imported by '<path>/src/index.ts'
@: rpt2: resolving './constants'
@: rpt2:     to '<path>/src/constants.ts'
@: rpt2: transpiling '<path>/src/constants.ts'
@: rpt2:     cache: 'c0821b0be34b449d7f93ba52a5b0708ea09e39f7'
@: rpt2:     cache miss
@: rpt2:     cache: 'c0821b0be34b449d7f93ba52a5b0708ea09e39f7'
@: rpt2:     cache miss
@: rpt2:     cache: 'c0821b0be34b449d7f93ba52a5b0708ea09e39f7'
@: rpt2:     cache miss
@: rpt2: generated declarations for '<path>/src/constants.ts'
@: rpt2: generating target 1
@: rpt2: rolling caches
@: rpt2: writing declarations for '<path>/src/index.ts' to '<path>/lib/index.d.ts'
@: rpt2: writing declarations for '<path>/src/index.ts' to '<path>/lib/index.d.ts.map'
@: rpt2: writing declarations for '<path>/src/constants.ts' to '<path>/lib/constants.d.ts'
@: rpt2: writing declarations for '<path>/src/constants.ts' to '<path>/lib/constants.d.ts.map'
@: rpt2: generating target 2
@: rpt2: rolling caches
@: rpt2: writing declarations for '<path>/src/index.ts' to '<path>/lib/index.d.ts'
@: rpt2: writing declarations for '<path>/src/index.ts' to '<path>/lib/index.d.ts.map'
@: rpt2: writing declarations for '<path>/src/constants.ts' to '<path>/lib/constants.d.ts'
@: rpt2: writing declarations for '<path>/src/constants.ts' to '<path>/lib/constants.d.ts.map'
@: created lib/index.js, lib/index.es.js in 1.2s
```
</details>

### LINKED ISSUE #211: Declarations not generated for type-only files not explicitly specified in `tsconfig`
Hello, again!

I've noticed the following behavior: TypeScript declarations are not generated for source modules from which only types are imported and which are not explicitly added to the project using `files` or `include` options in `tsconfig.json`.

## Project configuration

```json5
// tsconfig.json
{
  "compilerOptions": {
    "outDir": "dist/",
    "declarationDir": "dist/types/",
    "declaration": true
  },
  
  // specifying only entry-point
  "files": ["src/index.ts"]
}
```

```javascript
// rollup.config.js

import typeScriptPlugin2 from 'rollup-plugin-typescript2';

export default {
  input: 'src/index.ts',
  output: {
    file: 'dist/index.js',
    format: 'esm',
  },
  plugins: [
    typeScriptPlugin2({
      verbosity: 2,
      clean: true,
      useTsconfigDeclarationDir: true,
    }),
  ],
};
```

## Source files

```typescript
// src/index.ts

// importing only type symbol from './foo.ts'
import { Foo } from './foo';

export class Main {
  constructor(foo: Foo) {
    console.log(foo);
  }
}
```

```typescript
// src/foo.ts

// type symbol
export type Foo = 'foo';

// constant symbol (not imported)
export const defaultFoo: Foo = 'foo';
```

```typescript
// src/unused.ts

export type Unused = 'unused';
```

## Generated files

```javascript
// dist/index.js

var Main = /** @class */ (function () {
    function Main(foo) {
        console.log(foo);
    }
    return Main;
}());

export { Main };
```

```typescript
// dist/types/index.d.ts

// Error: TS2307: Cannot find module './foo'.
import { Foo } from './foo';

export declare class Main {
    constructor(foo: Foo);
}
```

* the `dist/types/unused.d.ts` is not generated, which is **GOOD**.
* however, the `dist/types/foo.d.ts` is not generated, which is **BAD**.

---

And if I would set `"include": ["src/"]`, the `dist/types/unused.d.ts` would be generated, however, it shouldn't, because it's not imported anywhere.

---

Our goal here is to specify only the entry point of our project and let the compiler to handle only source files that are actually used in the project and avoid processing, generating declarations and reporting errors for files that are not used (redundant).

### LINKED ISSUE #298: type-checking doesn't work on type-only modules
#### What happens and why it is wrong

When module contains only types (type,interface), and those types are being imported in other module, this plugin will omit those completely from type-checking which causes shipping invalid code to consumers.

🎬 Whole repro can be found here: https://stackblitz.com/edit/github-kgn16z-grsqrq?file=libs/test/rollup-config.js

1. run `yarn rollup:tsc` (uses this plugin with rollup) -> this will produce no Type errors 🚨 (Wrong)
2. run `yarn tsc:check`(uses raw tsc)  -> this will properly produce type errors ✅ (Correct, expected)

#### Source Code

```ts
// @filename src/index.ts
export * from './makeStyles';
```

```ts
// @filename src/makeStyles.ts

import { TestType } from './types';

export function makeStyles(): TestType {
  return {
    color: 'red',
  };
}
```

```ts
// @filename src/types.ts
interface CSS {
  backgroundColor: string;
}

export type TestType = {
  animationName?: CSS['background'];  // 🚨 this causes TS error
  color: string;
};
```
image

##### Versions

```text
typescript: ~4.4.3 => 4.4.4 
rollup@2.67.3
rollup-plugin-typescript2@0.31.2
```

#### rollup.config.js

<details>
  <summary>`rollup.config.js`: </summary>

```js
import * as path from 'path';
import ts from 'rollup-plugin-typescript2';
const repoRoot = path.resolve(__dirname, '..', '..');

const tsConfig = {
  check: true,
  tsconfig: 'libs/test/tsconfig.lib.json',
  useTsconfigDeclarationDir: true,
  verbosity: 4,
  tsconfigOverride: {
    compilerOptions: {
      rootDir: path.resolve(repoRoot, 'libs/test/src'),
      allowJs: false,
      declaration: true,
      declarationDir: path.resolve(repoRoot, 'out/tsc-dts'),
      paths: {
        test: ['libs/test/src/index.ts'],
      },
    },
  },
};

export default {
  input: path.resolve(__dirname, 'src/index.ts'),
  output: {
    file: path.resolve(repoRoot, 'out/bundle.js'),
    format: 'es',
  },
  plugins: [ts(tsConfig)],
};
```

</details>

#### tsconfig.json

<details>
  <summary>`tsconfig.json`: </summary>

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["node"]
  },
  "files": [
    "../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../node_modules/@nrwl/react/typings/image.d.ts"
  ],
  "exclude": [
    "**/*.spec.ts",
    "**/*.test.ts",
    "**/*.spec.tsx",
    "**/*.test.tsx",
    "**/*.spec.js",
    "**/*.test.js",
    "**/*.spec.jsx",
    "**/*.test.jsx"
  ],
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"]
}

```

</details>

#### package.json

<details>
  <summary>`package.json`: </summary>

</details>

#### plugin output with verbosity 4

<details>
  <summary>plugin output with verbosity 3: </summary>

```
rpt2: built-in options overrides: {
    "noEmitHelpers": false,
    "importHelpers": true,
    "noResolve": false,
    "noEmit": false,
    "inlineSourceMap": false,
    "outDir": "/home/projects/github-kgn16z-grsqrq/node_modules/.cache/rollup-plugin-typescript2/placeholder",
    "moduleResolution": 2,
    "allowNonTsExtensions": true
}
rpt2: parsed tsconfig: {
    "options": {
        "rootDir": "/home/projects/github-kgn16z-grsqrq/libs/test/src",
        "sourceMap": true,
        "declaration": true,
        "moduleResolution": 2,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "target": 2,
        "module": 99,
        "lib": [
            "lib.es2017.d.ts",
            "lib.dom.d.ts"
        ],
        "skipLibCheck": true,
        "skipDefaultLibCheck": true,
        "baseUrl": "/home/projects/github-kgn16z-grsqrq",
        "paths": {
            "test": [
                "libs/test/src/index.ts"
            ]
        },
        "pathsBasePath": "/home/projects/github-kgn16z-grsqrq/libs/test",
        "jsx": 4,
        "allowJs": false,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "noImplicitOverride": true,
        "noPropertyAccessFromIndexSignature": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "outDir": "/home/projects/github-kgn16z-grsqrq/node_modules/.cache/rollup-plugin-typescript2/placeholder",
        "types": [
            "node"
        ],
        "declarationDir": "/home/projects/github-kgn16z-grsqrq/out/tsc-dts",
        "configFilePath": "/home/projects/github-kgn16z-grsqrq/libs/test/tsconfig.lib.json",
        "noEmitHelpers": false,
        "noResolve": false,
        "noEmit": false,
        "inlineSourceMap": false,
        "allowNonTsExtensions": true
    },
    "fileNames": [
        "/home/projects/github-kgn16z-grsqrq/node_modules/@nrwl/react/typings/cssmodule.d.ts",
        "/home/projects/github-kgn16z-grsqrq/node_modules/@nrwl/react/typings/image.d.ts",
        "/home/projects/github-kgn16z-grsqrq/libs/test/src/index.ts",
        "/home/projects/github-kgn16z-grsqrq/libs/test/src/makeStyles.ts",
        "/home/projects/github-kgn16z-grsqrq/libs/test/src/types.ts"
    ],
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "raw": {
        "extends": "./tsconfig.json",
        "compilerOptions": {
            "outDir": "../../dist/out-tsc",
            "types": [
                "node"
            ],
            "rootDir": "/home/projects/github-kgn16z-grsqrq/libs/test/src",
            "allowJs": false,
            "declaration": true,
            "declarationDir": "/home/projects/github-kgn16z-grsqrq/out/tsc-dts",
            "paths": {
                "test": [
                    "libs/test/src/index.ts"
                ]
            }
        },
        "files": [
            "../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
            "../../node_modules/@nrwl/react/typings/image.d.ts"
        ],
        "exclude": [
            "**/*.spec.ts",
            "**/*.test.ts",
            "**/*.spec.tsx",
            "**/*.test.tsx",
            "**/*.spec.js",
            "**/*.test.js",
            "**/*.spec.jsx",
            "**/*.test.jsx"
        ],
        "include": [
            "**/*.js",
            "**/*.jsx",
            "**/*.ts",
            "**/*.tsx"
        ],
        "compileOnSave": false
    },
    "errors": [],
    "wildcardDirectories": {
        "/home/projects/github-kgn16z-grsqrq/libs/test": 1
    },
    "compileOnSave": false
}
rpt2: typescript version: 4.4.4
rpt2: tslib version: 2.3.1
rpt2: rollup version: 2.65.0
rpt2: rollup-plugin-typescript2 version: 0.31.1
rpt2: plugin options:
{
    "check": true,
    "tsconfig": "libs/test/tsconfig.lib.json",
    "useTsconfigDeclarationDir": true,
    "verbosity": 4,
    "tsconfigOverride": {
        "compilerOptions": {
            "rootDir": "/home/projects/github-kgn16z-grsqrq/libs/test/src",
            "allowJs": false,
            "declaration": true,
            "declarationDir": "/home/projects/github-kgn16z-grsqrq/out/tsc-dts",
            "paths": {
                "test": [
                    "libs/test/src/index.ts"
                ]
            }
        }
    },
    "clean": false,
    "cacheRoot": "/home/projects/github-kgn16z-grsqrq/node_modules/.cache/rollup-plugin-typescript2",
    "include": [
        "*.ts+(|x)",
        "**/*.ts+(|x)"
    ],
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "transformers": [],
    "tsconfigDefaults": {},
    "objectHashIgnoreUnknownHack": false,
    "cwd": "/home/projects/github-kgn16z-grsqrq",
    "typescript": "version 4.4.4"
}
rpt2: rollup config:
{
    "external": [],
    "input": "/home/projects/github-kgn16z-grsqrq/libs/test/src/index.ts",
    "plugins": [
        {
            "name": "rpt2"
        },
        {
            "name": "stdin"
        }
    ],
    "output": [
        {
            "file": "/home/projects/github-kgn16z-grsqrq/out/bundle.js",
            "format": "es",
            "plugins": []
        }
    ]
}
rpt2: tsconfig path: /home/projects/github-kgn16z-grsqrq/libs/test/tsconfig.lib.json
rpt2: included:
[
    "*.ts+(|x)",
    "**/*.ts+(|x)"
]
rpt2: excluded:
[
    "*.d.ts",
    "**/*.d.ts"
]
rpt2: Ambient types:
rpt2:     /home/projects/github-kgn16z-grsqrq/node_modules/@nrwl/react/typings/cssmodule.d.ts
rpt2:     /home/projects/github-kgn16z-grsqrq/node_modules/@nrwl/react/typings/image.d.ts
rpt2:     /home/projects/github-kgn16z-grsqrq/node_modules/@types/node/index.d.ts
rpt2: transpiling '/home/projects/github-kgn16z-grsqrq/libs/test/src/index.ts'
rpt2:     cache: '/home/projects/github-kgn16z-grsqrq/node_modules/.cache/rollup-plugin-typescript2/rpt2_4b2584b8fec2cb2070a57cc5fc1737a58e40ee79/code/cache/c054c5afccc541591135fb48ef93844cf144244d'
rpt2:     cache hit
rpt2:     cache: '/home/projects/github-kgn16z-grsqrq/node_modules/.cache/rollup-plugin-typescript2/rpt2_4b2584b8fec2cb2070a57cc5fc1737a58e40ee79/syntacticDiagnostics/cache/c054c5afccc541591135fb48ef93844cf144244d'
rpt2:     cache hit
rpt2:     cache: '/home/projects/github-kgn16z-grsqrq/node_modules/.cache/rollup-plugin-typescript2/rpt2_4b2584b8fec2cb2070a57cc5fc1737a58e40ee79/semanticDiagnostics/cache/c054c5afccc541591135fb48ef93844cf144244d'
rpt2:     cache hit
rpt2: generated declarations for '/home/projects/github-kgn16z-grsqrq/libs/test/src/index.ts'
rpt2: dependency '/home/projects/github-kgn16z-grsqrq/libs/test/src/makeStyles.ts'
rpt2:     imported by '/home/projects/github-kgn16z-grsqrq/libs/test/src/index.ts'
rpt2: resolving './makeStyles' imported by '/home/projects/github-kgn16z-grsqrq/libs/test/src/index.ts'
rpt2:     to '/home/projects/github-kgn16z-grsqrq/libs/test/src/makeStyles.ts'
rpt2: transpiling '/home/projects/github-kgn16z-grsqrq/libs/test/src/makeStyles.ts'
rpt2:     cache: '/home/projects/github-kgn16z-grsqrq/node_modules/.cache/rollup-plugin-typescript2/rpt2_4b2584b8fec2cb2070a57cc5fc1737a58e40ee79/code/cache/f1f8bd7cd1ae728a9fe42101454aeb9263d56bc2'
rpt2:     cache hit
rpt2:     cache: '/home/projects/github-kgn16z-grsqrq/node_modules/.cache/rollup-plugin-typescript2/rpt2_4b2584b8fec2cb2070a57cc5fc1737a58e40ee79/syntacticDiagnostics/cache/f1f8bd7cd1ae728a9fe42101454aeb9263d56bc2'
rpt2:     cache hit
rpt2:     cache: '/home/projects/github-kgn16z-grsqrq/node_modules/.cache/rollup-plugin-typescript2/rpt2_4b2584b8fec2cb2070a57cc5fc1737a58e40ee79/semanticDiagnostics/cache/f1f8bd7cd1ae728a9fe42101454aeb9263d56bc2'
rpt2:     cache hit
rpt2: generated declarations for '/home/projects/github-kgn16z-grsqrq/libs/test/src/makeStyles.ts'
rpt2: generating target 1
rpt2: rolling caches
rpt2: generating missed declarations for '/home/projects/github-kgn16z-grsqrq/node_modules/@nrwl/react/typings/cssmodule.d.ts'
rpt2: generating missed declarations for '/home/projects/github-kgn16z-grsqrq/node_modules/@nrwl/react/typings/image.d.ts'
rpt2: generating missed declarations for '/home/projects/github-kgn16z-grsqrq/libs/test/src/types.ts'
rpt2: emitting declarations for '/home/projects/github-kgn16z-grsqrq/libs/test/src/index.ts' to '/home/projects/github-kgn16z-grsqrq/out/tsc-dts/index.d.ts'
rpt2: emitting declarations for '/home/projects/github-kgn16z-grsqrq/libs/test/src/makeStyles.ts' to '/home/projects/github-kgn16z-grsqrq/out/tsc-dts/makeStyles.d.ts'
rpt2: emitting declarations for '/home/projects/github-kgn16z-grsqrq/libs/test/src/types.ts' to '/home/projects/github-kgn16z-grsqrq/out/tsc-dts/types.d.ts'
created out/bundle.js in 949ms
```

</details>

### Related issues

https://github.com/ezolenko/rollup-plugin-typescript2/issues/211

### LINKED ISSUE #409: some type-only TS files are ignored when using `tsconfig` `files`?
## What happens and why it is incorrect

there are many files ending in `*.ts` in the src, but only some have been transpiled

1. Does `tsc` have the same output? If so, please explain why this is incorrect behavior

NO， `tsc` run as expectly.
image

here's file structure:
image

but rpt2 seems to ignore the file named `component.ts`:
image

### Versions

```text
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 59.11 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.4/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
  npmPackages:
    rollup: ^2.45.2 => 2.45.2
    rollup-plugin-typescript2: ^0.30.0 => 0.30.0
    typescript: ^4.3.5 => 4.3.5
  npmGlobalPackages:
    typescript: 4.3.5
```

<details>
  <summary><h4><code>rollup.config.js</code></h4>: </summary>

```js
import { nodeResolve } from '@rollup/plugin-node-resolve';

import replace from '@rollup/plugin-replace';
import postcss from 'rollup-plugin-postcss';
import image from '@rollup/plugin-image';
import ts from 'rollup-plugin-typescript2';
import dts from 'rollup-plugin-dts';
import json from '@rollup/plugin-json';
import alias from '@rollup/plugin-alias';
import autoExternal from 'rollup-plugin-auto-external';
import path from 'path';
import importCss from './rollup-plugin-import-css';

const resolve = (...dirs) => path.resolve(__dirname, '../', ...dirs);

function toUpperCase(match) {
  return match.replace('-', '').toUpperCase();
}

export default [
  {
    input: resolve('src/lib/index.tsx'),
    output: [
      {
        file: resolve('dist/index.esm.js'),
        format: 'es',
        sourcemap: true,
      },
    ],

    external: id => {
      try {
        const idSourcePath = require.resolve(id, { paths: [resolve()] });
        return idSourcePath && idSourcePath.includes('node_modules');
      } catch (error) {
        return false;
      }
    },
    plugins: [
      ts({
        check: false,
        tsconfig: resolve('tsconfig.json'),
        tsconfigOverride: {
          compilerOptions: { declaration: true, declarationDir: resolve('dist/type') },
        },
        verbosity: 2,
        useTsconfigDeclarationDir: true,
        include: ['*.ts+(|x)', '**/*.ts+(|x)', '*.js+(|x)', '**/*.js+(|x)'],
      }),
      image(),
      postcss({
        extensions: ['.css', '.scss', '.less'],
        autoModules: true,
        extract: 'index.css',
        namedExports(name) {
          let reg = /-[a-z]/g;
          const temp = name.replace(reg, toUpperCase);
          return temp;
        },
      }),
      json(),
      alias({
        entries: [
          {
            find: 'src',
            replacement: resolve('src'),
          },
        ],
      }),
      nodeResolve({
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
        // some package.json files have a "browser" field which specifies
        // alternative files to load for people bundling for the browser. If
        // that's you, either use this option or add "browser" to the
        // "mainfields" option, otherwise pkg.browser will be ignored
        browser: true,
        preferBuiltins: true,
        mainFields: ['browser', 'jsnext', 'module', 'main'],
      }),
      replace({
        'process.env.NODE_ENV': JSON.stringify('development'),
        'process.env.SEMI_ICON_LAZY_LOAD': true,
        preventAssignment: true,
      }),
      autoExternal({
        packagePath: resolve(),
      }),
      importCss(),
    ],
  },
  {
    input: resolve('dist/type/src/lib/index.d.ts'),
    external: id => {
      try {
        const idSourcePath = require.resolve(id, { paths: [resolve()] });
        return idSourcePath && idSourcePath.includes('node_modules');
      } catch (error) {
        return false;
      }
    },
    output: [{ file: resolve('dist/index.d.ts'), format: 'es' }],
    plugins: [dts()],
  },
];

```

</details>

<details>
  <summary><h4><code>tsconfig.json</code></h4>: </summary>

```json5
{
  "compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "lib": ["es7", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "rootDir": "./",
    "baseUrl": "./src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": false,
    "noImplicitAny": false,
    "importHelpers": true,
    "strictNullChecks": false,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noEmit": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": false,
    "paths": {
      "@ies/kefu-editor": ["src/lib/*"]
    },
    "plugins": [
      {
        "transform": "ts-optchain/transform"
      }
    ]
  },
  "typeRoots": ["node", "node_modules/@types", "./src/typings"],
  "exclude": ["node_modules"]
}

```

</details>

<details>
  <summary><h4><code>package.json</code></h4>: </summary>

```json

```

</details>

<details>
  <summary><h4>plugin output with verbosity 3</h4>: </summary>

```text
/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx → dist/index.esm.js...
rpt2: built-in options overrides: {
    "noEmitHelpers": false,
    "importHelpers": true,
    "noResolve": false,
    "noEmit": false,
    "inlineSourceMap": false,
    "outDir": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/.cache/rollup-plugin-typescript2/placeholder",
    "moduleResolution": 2,
    "allowNonTsExtensions": true
}
rpt2: parsed tsconfig: {
    "options": {
        "isolatedModules": false,
        "declaration": true,
        "target": 2,
        "module": 99,
        "lib": [
            "lib.es2016.d.ts",
            "lib.dom.d.ts"
        ],
        "sourceMap": true,
        "allowJs": true,
        "jsx": 2,
        "moduleResolution": 2,
        "experimentalDecorators": true,
        "rootDir": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable",
        "baseUrl": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src",
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "noImplicitThis": false,
        "noImplicitAny": false,
        "importHelpers": true,
        "strictNullChecks": false,
        "suppressImplicitAnyIndexErrors": true,
        "noUnusedLocals": true,
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": false,
        "paths": {
            "@ies/kefu-tag-table": [
                "src/lib/*"
            ]
        },
        "plugins": [
            {
                "transform": "ts-optchain/transform"
            }
        ],
        "declarationDir": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/dist/type",
        "configFilePath": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/tsconfig.json",
        "pathsBasePath": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable",
        "noEmitHelpers": false,
        "noResolve": false,
        "noEmit": false,
        "inlineSourceMap": false,
        "outDir": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/.cache/rollup-plugin-typescript2/placeholder",
        "allowNonTsExtensions": true
    },
    "fileNames": [
        "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx"
    ],
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "raw": {
        "files": [
            "src/lib/index.tsx"
        ],
        "compilerOptions": {
            "isolatedModules": false,
            "declaration": true,
            "target": "es6",
            "module": "esnext",
            "lib": [
                "es7",
                "dom"
            ],
            "sourceMap": true,
            "allowJs": true,
            "jsx": "react",
            "moduleResolution": "node",
            "experimentalDecorators": true,
            "rootDir": "./",
            "baseUrl": "./src",
            "forceConsistentCasingInFileNames": true,
            "noImplicitReturns": true,
            "noImplicitThis": false,
            "noImplicitAny": false,
            "importHelpers": true,
            "strictNullChecks": false,
            "suppressImplicitAnyIndexErrors": true,
            "noUnusedLocals": true,
            "allowSyntheticDefaultImports": true,
            "esModuleInterop": false,
            "paths": {
                "@ies/kefu-tag-table": [
                    "src/lib/*"
                ]
            },
            "plugins": [
                {
                    "transform": "ts-optchain/transform"
                }
            ],
            "declarationDir": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/dist/type"
        },
        "typeRoots": [
            "node",
            "node_modules/@types",
            "./src/typings"
        ],
        "exclude": [
            "node_modules"
        ],
        "compileOnSave": false
    },
    "errors": [],
    "wildcardDirectories": {},
    "compileOnSave": false
}
rpt2: typescript version: 4.3.5
rpt2: tslib version: 2.1.0
rpt2: rollup version: 2.45.2
rpt2: rollup-plugin-typescript2 version: 0.30.0
rpt2: plugin options:
{
    "check": false,
    "tsconfig": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/tsconfig.json",
    "tsconfigOverride": {
        "compilerOptions": {
            "declaration": true,
            "declarationDir": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/dist/type"
        }
    },
    "verbosity": 3,
    "useTsconfigDeclarationDir": true,
    "include": [
        "*.ts+(|x)",
        "**/*.ts+(|x)",
        "*.js+(|x)",
        "**/*.js+(|x)"
    ],
    "clean": false,
    "cacheRoot": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/.cache/rollup-plugin-typescript2",
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "transformers": [],
    "tsconfigDefaults": {},
    "objectHashIgnoreUnknownHack": false,
    "cwd": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable",
    "typescript": "version 4.3.5"
}
rpt2: rollup config:
{
    "input": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx",
    "plugins": [
        {
            "name": "rpt2"
        },
        {
            "name": "image"
        },
        {
            "name": "postcss"
        },
        {
            "name": "json"
        },
        {
            "name": "alias"
        },
        {
            "name": "node-resolve"
        },
        {
            "name": "replace"
        },
        {
            "name": "auto-external"
        },
        {},
        {
            "name": "stdin"
        }
    ],
    "output": [
        {
            "file": "/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/dist/index.esm.js",
            "format": "es",
            "plugins": [],
            "sourcemap": true
        }
    ]
}
rpt2: tsconfig path: /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/tsconfig.json
rpt2: included:
[
    "*.ts+(|x)",
    "**/*.ts+(|x)",
    "*.js+(|x)",
    "**/*.js+(|x)"
]
rpt2: excluded:
[
    "*.d.ts",
    "**/*.d.ts"
]
rpt2: Ambient types:
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/babel__core/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/babel__generator/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/babel__template/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/babel__traverse/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/color-name/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/css-modules-loader-core/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/estree/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/graceful-fs/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/hast/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/istanbul-lib-coverage/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/istanbul-lib-report/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/istanbul-reports/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/jest/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/json-schema/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/mdast/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/node/ts3.7/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/normalize-package-data/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/parse-json/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/parse5/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/prettier/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/prop-types/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/q/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/react/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/react-dom/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/resolve/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/stack-utils/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/unist/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/yargs/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/yargs-parser/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/json-schema/index.d.ts
rpt2:     /Users/bytedance/node_modules/@types/json5/index.d.ts
rpt2:     /Users/bytedance/node_modules/@types/minimist/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/node/ts3.7/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/normalize-package-data/index.d.ts
rpt2:     /Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/@types/parse-json/index.d.ts
rpt2: ambient types changed, redoing all semantic diagnostics
rpt2: transpiling '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx'
rpt2:     cache: '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/.cache/rollup-plugin-typescript2/rpt2_9e69c65b2d74fee0ad388d42568ea4ce7ba1b27d/code/cache/7cdbf1c7db69c2fd53815824bca49513a129c642'
rpt2:     cache miss
rpt2: generated declarations for '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx'
rpt2: dependency '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/utils.ts'
rpt2:     imported by '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx'
rpt2: resolving './utils' imported by '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx'
rpt2:     to '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/utils.ts'
rpt2: dependency '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/mock.ts'
rpt2:     imported by '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx'
rpt2: resolving './mock' imported by '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx'
rpt2:     to '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/mock.ts'
rpt2: transpiling '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/mock.ts'
rpt2:     cache: '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/.cache/rollup-plugin-typescript2/rpt2_9e69c65b2d74fee0ad388d42568ea4ce7ba1b27d/code/cache/a3be5c51ebb3fef03fc9a43c539d188ad1577216'
rpt2:     cache hit
rpt2: generated declarations for '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/mock.ts'
rpt2: transpiling '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/utils.ts'
rpt2:     cache: '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/node_modules/.cache/rollup-plugin-typescript2/rpt2_9e69c65b2d74fee0ad388d42568ea4ce7ba1b27d/code/cache/d1d6e9acec5e9e0b4392fcbc5bf623dab081aa31'
rpt2:     cache hit
rpt2: generated declarations for '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/utils.ts'

rpt2: generating target 1
rpt2: rolling caches
rpt2: emitting declarations for '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/index.tsx' to '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/dist/type/src/lib/index.d.ts'
rpt2: emitting declarations for '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/mock.ts' to '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/dist/type/src/lib/mock.d.ts'
rpt2: emitting declarations for '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/src/lib/utils.ts' to '/Users/bytedance/Public/helpdesk-semi-ui/packages/KefuCascaderTable/dist/type/src/lib/utils.d.ts'
(!) Broken sourcemap
https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as 'at position 9') should generate accompanying sourcemaps
created dist/index.esm.js in 2.7s

User/dist/type/src/lib/index.d.ts → dist/index.d.ts...
[!] Error: Could not resolve './component' from dist/type/src/lib/index.d.ts
Error: Could not resolve './component' from dist/type/src/lib/index.d.ts
```

</details>

### PR DESCRIPTION
**Pull request by agilgur5**
~**NOTE**: this is built on top of #403 as it changes its code a bit. #403 is itself built on top of #386. As such, I've marked this PR as "Draft" until those PRs are merged.~
Rebased on top and marked as ready for review. (surprisingly clean rebase)

Also this might be the first time this repo has more open PRs than open issues 😮 

## Summary

Completely handle the long-standing issue of type-only imports
- Uses the solution I proposed in my root cause analysis in https://github.com/ezolenko/rollup-plugin-typescript2/issues/298#issuecomment-1146658442
- Fixes #7 as all type-only imports go through the `resolveId` hook now, which adds them to the cache (calls `cache().setDependency`)
- Fixes #211
  - And its various duplicates: fixes #24, fixes #106, fixes #409
- Fully fixes the most common issue that I mentioned in https://github.com/ezolenko/rollup-plugin-typescript2/pull/311#issuecomment-1115491161, type-only imports
- Related to #345
  - _That_ PR fixed #298 and the latter half of #254 for their specific use-cases as they happen to use `include` globs, but _this_ PR fixes it in all other scenarios as well (namely when using [`files`](https://www.typescriptlang.org/tsconfig#files) instead of `include` globs)

## Details

- `result.references` is populated by `ts.preProcessFile`; i.e. this is TS discovering all imports, instead of Rollup
  - TS's imports include type-only files as TS understands those (whereas they aren't emitted in the JS for Rollup to see, since, well, they produce no JS)
  - so we can pipe all these through Rollup's `this.resolve` and `this.load` to make them go through Rollup's `resolveId` -> `load` -> `transform` hooks
    - this makes sure that other plugins on the chain get to resolve/transform them as well
    - and it makes sure that we run the same code that we run on all other files on type-only ones too
      - for instance: adding declarations, type-checking, setting them as deps in the cache graph, etc
      - yay recursion!
        - also add check for circular references b/c of this recursion (which Rollup docs confirm is necessary, per in-line comment)
    - and Rollup ensures that there is no perf penalty if a regular file is processed this way either, as it won't save the hook results when it appears in JS (i.e. Rollup's module graph)
      - we are checking more files though, so that in and of itself means potential slowdown for better correctness

- add a test for this that uses a `tsconfig` `files` array, ensuring that the `include` workaround won't cover these type-only files
  - this test fails without the new code added to `index` in this commit
  - also add another file, `type-only-import-import`, to the `no-errors` fixture to ensure that we're not just checking imports one level deep, and actually going through type-only imports of type-only imports as well
    - the declaration check for this will fail if type-only imports are not handled recursively
      - an initial version of this fix that I had that didn't call `this.load` failed this check

- refactor(test): make the integration tests more resilient to output ordering changes
  - due to the eager calls to `this.load`, the ordering of declaration and declaration map outputs in the bundle changed
    - and bc TS's default ordering of imports seems to differ from Rollup's
  - note that this only changed the order of the "bundle output" object -- which Rollup doesn't guarantee ordering of anyway
    - all files are still in the bundle output and are still written to disk
    - for example, the `watch` tests did not rely on this ordering and as such did not need to change due to the ordering change
  - create a `findName` helper that will search the `output` array instead, ensuring that most ordering does not matter
    - we do still rely on `output[0]` being the bundled JS (ESM) file, however

- refactor(test): go through a `files` array for tests that check for multiple files instead of listing out each individual check
  - this makes the tests more resilient to fixture changes as well (i.e. addition / deletion of files)
  - create `no-errors.ts` that exports a list of files for this fixture
    - didn't need to do the same for `errors.ts` as of yet; may do so in the future though
    
## Review Notes

1. I double-checked that the [`transform` hook](https://github.com/rollup/rollup/blob/v1.18.0/docs/05-plugin-development.md#transform) could be async in the minimum Rollup version we support.
    - The in-line linked docs are from Rollup `v1.18.0` as I couldn't find a mention of async in the `CHANGELOG.md`.
  
1. This could be considered "breaking", but the bundle ordering should realistically not affect anyone (only tests that rely on ordering, which was never guaranteed by Rollup as `this.load` could be called by any plugin at any time) and this should only be _additive_, in that it increases the number of files that are type-checked / generated declarations for.
    - So personally, I don't think this needs a minor bump. If it does get a minor bump, we should release a patch before merging this as I've had a bunch of other fixes in the past month or two that have not yet been released.

1. Related to that, I specifically _did not_ touch the "missed" type-checking / declaration generation that uses `parsedConfig.fileNames` to partly workaround this issue (i.e. #345 and the respective declaration generation block)
    - Removing those would almost certainly be considered breaking, since it could remove some files from type-checking / declaration generation. See also the "Note" in #345
    - While #211 says rpt2 shouldn't process those, I don't necessarily agree with that statement, because `tsc` will process those. Not processing `parsedConfig.fileNames` would mean only processing the Rollup `input`, acting _as if_ the `tsconfig` had `files` with only that single file from the Rollup `input` in it. That behavior could make sense to some, but not others, so I'm not sure that that's ideal.
    The "Note" in #345 mentions how users may use `include` globs or `files` arrays to list _other_ files they want type-checking and declarations. These files may not be considered part of the Rollup "bundle" however, so I could see an argument for either direction.
    - In any case, this has not been changed for now. If warranted, we could remove this in a _separate_ PR, and _that one_ would be breaking, but I would not say that _this_ PR in its current state is breaking.
  
## References

Will add some more downstream issues in a list here ([TBD])

### CODE REVIEW

**Comment by agilgur5** [comment]
> * While #211 says rpt2 shouldn't process those, I don't necessarily agree with that statement, because `tsc` will process those. Not processing `parsedConfig.fileNames` would mean only processing the Rollup `input`, acting _as if_ the `tsconfig` had `files` with only that single file from the Rollup `input` in it. That behavior could make sense to some, but not others, so I'm not sure that that's ideal. [...] These files may not be considered part of the Rollup "bundle" however, so I could see an argument for either direction.

I happened to stumble upon this yesterday -- it turns out that `ts-loader` (in Webpack-land) actually does this as well, acting like `tsc` _by default_, with the [`onlyCompileBundledFiles`](https://github.com/TypeStrong/ts-loader#onlycompilebundledfiles) option available to do, as named, only consider files that are part of the "bundle".

So doing the same as `ts-loader`'s default is probably optimal community-wise. I don't think we necessarily need the `onlyCompileBundledFiles` option though, as the same is achievable by changing `tsconfig` `files` (in a `tsconfigOverride`, for instance)

File: src/index.ts [hunk 1]
```diff
@@ -194,8 +198,9 @@ const typescript: PluginImpl<RPT2Options> = (options) =>
 			return null;
 		},
 
-		transform(code, id)
+		async transform(code, id)
 		{
+			transformedFiles.add(id);
```
Comment (agilgur5) [inline src/index.ts:203]: I was thinking that this (or the `has` check below) might need normalization, but I actually don't think that's needed, because we use Rollup's native `id`s in both usages, so it's all Rollup and there's no TS <-> Rollup conversion needed.

A test with a circular import would be good to confirm that though.

I should probably add a comment here with that for future readers as well, since normalization is such a common gotcha we have deal with

Comment (agilgur5) [reply src/index.ts]: added an in-line comment

File: src/index.ts [hunk 2]
```diff
@@ -205,8 +209,10 @@ const typescript: PluginImpl<RPT2Options> = (options) =>
 			return null;
 		},
 
-		transform(code, id)
+		async transform(code, id)
```
[the remark this answers is not in the document]
Comment (agilgur5) [reply src/index.ts:212]: No, nothing *has* to be async, just that things *can* be async now. Note that all the tests still pass etc.

The only thing that calls `transform` is Rollup itself or context functions like `this.load`. So those need to handle `await`ing (as the loop itself does), but nothing else has to.

So other than the code that was changed in this PR, nothing else has to change.

I know we still have the nuance that TS is fully synchronous while Rollup is async, but that's only relevant when, for instance, the `LanguageServer` has to call a Rollup method.
This case is the opposite; i.e. async is compatible with sync but not the other way around.

**Comment by ezolenko** [comment]
There is a conflict with previous PR, but otherwise looks good

**Comment by agilgur5** [comment]
Fixed the conflict 👍

**Comment by agilgur5** [comment]
Welp, realized while testing something that `this.load` was only added in Rollup [`2.60.0`](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#2600), _much_ later than `this.resolve`...

That's my bad, adding a hotfix now to make this backward-compatible with our minimum `1.26.3` requirement
